views.cache.custom_tag:
  type: mapping
  mapping:
    type:
      type: string
    options:
      type: mapping
      mapping:
        custom_tag:
          type: string
          label: 'Custom tag list'

views.argument_validator.entity:*:
  type: views.argument_validator_entity
